// Generated by CoffeeScript 1.7.1
(function() {
  var homepage, utils;

  utils = require("../../../modules/utils");

  module.exports = homepage = {
    index: function(request, response) {
      var templateValues;
      utils.log("hr");
      utils.log("info", "In homepage.index()");
      templateValues = {
        msg: "hello world"
      };
      return response.render("homepage/index", templateValues);
    }
  };

}).call(this);
