// Generated by CoffeeScript 1.7.1
(function() {
  var express, homepage, router;

  express = require("express");

  router = express.Router();

  homepage = require("./homepage");

  router.get('/', homepage.index);

  module.exports = router;

}).call(this);
